source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target 'WBGuideCover_Example' do
  pod 'WBGuideCover', :path => '../'

  target 'WBGuideCover_Tests' do
    inherit! :search_paths
  end
end
